services:
  postgres:
    image: postgres:16-alpine
    container_name: weddq_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: weddq
      POSTGRES_PASSWORD: ab6f2959838dfad5efe1ac79885fb4a62414
      POSTGRES_DB: weddq
    ports:
      - "5433:5432"
    volumes:
      - weddq_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U weddq -d weddq"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  weddq_pgdata:
